// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var greetingMessage = "Hello World";

console.log(greetingMessage);

exports.greetingMessage = greetingMessage;
/*  Not a pure module */
