service: greenlabs-sinsun-market

frameworkVersion: '2'
useDotenv: true

provider:
  name: aws
  runtime: java11
  lambdaHashingVersion: 20201221
  region: ap-northeast-2
  memorySize: 512
  timeout: 30
  logRetentionInDays: 14
  tags:
    VERSION: ${file(target/target.json):version}

package:
  artifact: ${file(target/target.json):file}

functions:
  to-sqs:
    handler: to_sqs::handler
    role: arn:aws:iam::140131123595:role/lambda-s3-sqs
    environment:
      SQS_URL: { Ref: TestFifo }

  from-sqs:
    handler: from_sqs::handler
    role: arn:aws:iam::140131123595:role/lambda-s3-sqs
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - TestFifo
              - Arn

resources:
  Resources:
    TestFifo:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: test-${sls:stage}.fifo
        FifoQueue: true
        VisibilityTimeout: 30
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt:
              - TestFifoDLQ
              - Arn
          maxReceiveCount: 1

    TestFifoDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: test-dlq-${sls:stage}.fifo
        FifoQueue: true


