# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: serverless-test
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: java11
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-northeast-2
  profile: me
  memorySize: 512
  timeout: 30
  kmsKeyArn: arn:aws:iam::140131123595:role/lambda-s3-sqs
  logRetentionInDays: 14

package:
  artifact: lambda.zip

functions:
  serverless:
    handler: core::handler
    events:
      - schedule:
          name: every-5-minutes
          rate: rate(5 minutes)

