version: '3.7'

services:
  mongodb: # 서비스명
    image: mongo
    container_name: "mongodb"
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "0000"
